### ISSUE TITLE
Feature request: add a zip operator

### ISSUE THREAD

**Issue by obenkenobi** [joamaki/goreactive#1]
Similar to how zip works on [rxjs](https://www.learnrxjs.io/learn-rxjs/operators/combination/zip) or even [RxGo](https://github.com/ReactiveX/RxGo/blob/master/doc/zipfromiterable.md), I would like to have zip functions created for this library.

The method would take 2 or more observables, and then returns an observable that has a tuple or a slice of combined values like how this would be done in rxjs. 

I suggest having more than one method based on how many observables intended to be passed.

For example `zip2(observable[V1], observable[V2])` returns an `observable[Tuple[V1, V2]]`.
Then zip would take `zip(...observable[any])` returns an `observable[[]any]`

Now I am aware observables of interfaces of `any` type was not the point of this project but if we want to take an unbounded array of observables that may contain many different types, an `any` type makes the most sense in that scenario.

**Comment by joamaki** [comment]
Hey, thanks for the request. I added Zip2. 

I think the more general form isn't so often useful and I'd like to avoid `any` in the API. In cases where one needs to zip a lot of observables, it's likely better to just do e.g. `ToChannel` on them and select on the channels (e.g. see how ZIp2 is implemented).
